[package]
name = "sudoku_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.12.1"
rand = { version = "0.8.5", features = ["std_rng"] }

[profile.release]
opt-level = 3
strip = true